name: Vérification utilisateurs indisponibles

on:
  workflow_dispatch:      # Permet de lancer manuellement
  repository_dispatch:    # Permet à cron-job.org d'appeler l'URL
    types: [run-script]

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run script
        run: node index.js
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
